### ISSUE TITLE
TypeError in RDF - Related modules

### ISSUE THREAD

**Issue by davidjguru** [openeuropa/rdf_skos#26]
Hello, I'm David Rodríguez, from the Europass 2 dev team. We're working with Open Europa for the last three months and today talking with Rob Harings about a historical problem with RDF listing,he recommended me to create this issue. Let's go. 

**First,** we have installed the oe_content module following the instructions from [https://github.com/openeuropa/oe_content/blob/master/README.md](https://github.com/openeuropa/oe_content/blob/master/README.md).

![Selection_284](https://user-images.githubusercontent.com/21089086/64320718-6adbbe80-cfbf-11e9-9bc5-7921b65d0207.png)

**Second,** All our four Docker Containers are working and connected on a Docker-Compose Network, including the fourth container, the SPARQL Container. 

![Selection_286](https://user-images.githubusercontent.com/21089086/64320905-c3ab5700-cfbf-11e9-90b8-a9d2ea993c40.png)

**Third,** Our .env file set the alias for the fourth SPARQL container and the values for database connection are loaded correctly in settings.php using the task runner. 

![Selection_288](https://user-images.githubusercontent.com/21089086/64321101-2866b180-cfc0-11e9-9af1-5eb0dc5dcb58.png)

![Selection_287](https://user-images.githubusercontent.com/21089086/64321113-30265600-cfc0-11e9-8576-bc31161068ac.png)

**Fourth,** We have enabled all the OE modules and the oe_content sub-family of modules.

![Selection_285](https://user-images.githubusercontent.com/21089086/64321228-7085d400-cfc0-11e9-86f7-f7bddfbd1ca2.png)

**Fifth**, on a trial basis, we can access and make available certain types of content stored in SPARQL, such as the use of "Author" in nodes. 

![Selection_289](https://user-images.githubusercontent.com/21089086/64321397-be024100-cfc0-11e9-9cee-d9a362520088.png)

**Sixth,** We can see an access to "RDF listing" in two links from the User Interface, but unexpectedly, this cause a crash in the platform and get a WSOD in our installation. 

![Selection_290](https://user-images.githubusercontent.com/21089086/64321658-4254c400-cfc1-11e9-9988-aa0b28c3e302.png)

Marking a Issue RDF-related: 

![Selection_292](https://user-images.githubusercontent.com/21089086/64321820-9fe91080-cfc1-11e9-84ca-1cde70878c1a.png)

**Details in /admin/reports/dblog/event/ from the Watchdog table**

```
TypeError: Return value of Drupal\rdf_entity\RdfGraphHandler::getEntityTypeGraphUris() must be of the type array, null returned in Drupal\rdf_entity\RdfGraphHandler->getEntityTypeGraphUris() (line 164 of /var/www/html/web/modules/contrib/rdf_entity/src/RdfGraphHandler.php) #0 ;

/var/www/html/web/modules/contrib/rdf_entity/src/RdfGraphHandler.php(182): Drupal\rdf_entity\RdfGraphHandler->getEntityTypeGraphUris('rdf_entity', Array) #1;

/var/www/html/web/modules/contrib/rdf_entity/src/Entity/Query/Sparql/Query.php(203): Drupal\rdf_entity\RdfGraphHandler->getEntityTypeGraphUrisFlatList('rdf_entity', Array) #2; 

/var/www/html/web/modules/contrib/rdf_entity/src/Entity/Query/Sparql/Query.php(149): Drupal\rdf_entity\Entity\Query\Sparql\Query->prepare() #3; 

/var/www/html/web/modules/contrib/rdf_entity/src/Entity/Controller/RdfListBuilder.php(94): Drupal\rdf_entity\Entity\Query\Sparql\Query->execute() #4; 

/var/www/html/web/core/lib/Drupal/Core/Entity/EntityListBuilder.php(86): Drupal\rdf_entity\Entity\Controller\RdfListBuilder->getEntityIds() #5 
```

**Comment by brummbar** [comment]
Rdf entity is not a dependency anymore, so the tab is gone too.
