### ISSUE TITLE
Update from 0.12.0 to 1.0.0-alpha17 fails

### ISSUE THREAD

**Issue by ansergeyg** [openeuropa/rdf_skos#70]
Hi guys,

So we try to conduct major updates for our openeuropa modules like countries/blocks/content etc. , we noticed that this module requires particular update.
 
In the readme file it is said that we need to require:

composer require drupal/sparql_entity_storage:dev-empty-module

before updating the module itself. But there is no dev-empty-module version. There are only alpha versions.
We tried to install the latest version of this module to see if it works, but immediately faced an issue in the rdf_entity module.

Could you please take a look at this and advise us how to resolve this conflict?

Regards, Sergey

**Comment by kimlop** [comment]
Hi @ansergeyg I solved by adding the module repository directly in composer.json. 
In this way you will be able to download the dev-empty-code branch which is not currently published on packagist 

```bash
 "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        {
            "type": "git",
            "url": "https://git.drupalcode.org/project/sparql_entity_storage.git"
        }
    ],
```

**Comment by ansergeyg** [comment]
Hi @kimlop ,
Thanks for sharing the fix. I also found out that you cannot simply require a module by its branch name if there is no source.
However the problem seems to be even bigger than that. The first step was unclear, but there are two more step to go. And they are also not clear.
I don't know what is the build procedure for you but we use specialized toolkit to build our project and also specialized deploying workflow which makes it even more complicated to survive this kind of module refactoring (requiring three step (luckily) upgrade later).
If someone faces the same issues: here is the fix for the second step:

https://github.com/ec-europa/rdf_entity/issues/139

PS: To me openeuropa team should really update the manual for this module. Other wise the chain upgrade to any dependent oe modules are not possible. Even worse, mandatory upgrade to drupal 9 is impossible.
Regards, Sergey
